node1: &dataset_size 50000
node1: &bs 100


dataset_size: *dataset_size
name: 'NoisedSGD'
kwargs:
  lr: .5
  dataset_size: *dataset_size
  momentum: 0.
  weight_decay: 0.001
batcher_name: MiniBatcher
batcher_kwargs:
  batch_size: *bs
max_train_iters: 1000000
# lrsche: [[3000, .1],[10000, .1]]
# lrpoly: [0.2, 1, 0.55] #(a,b,g) for a(b+t)^(-g)