dataset_size: 50000
name: 'optim.SGD'
kwargs:
  lr: 0.5
  momentum: 0.0
  weight_decay: 0.001
batcher_name: MiniBatcher
batcher_kwargs:
  batch_size: 100
max_train_iters: 1000000
# lrsche: [[3000, .1],[10000, .1]]