node1: &dataset_size 100
node1: &bs 100


dataset_size: *dataset_size
name: 'NoisedSGD'
kwargs:
  lr: .005
  dataset_size: *dataset_size
  momentum: 0.9
  weight_decay: 0.001
batcher_name: MiniBatcher
batcher_kwargs:
  batch_size: *bs
max_train_iters: 1000000
# lrsche: [[3000, .1],[10000, .1]]